# Generated by Django 4.1.3 on 2023-02-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_no', models.IntegerField(verbose_name='데이터 번호')),
                ('name', models.CharField(max_length=100, verbose_name='데이터 이름')),
            ],
        ),
    ]
